name: Compilar SEGOVIA TV

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Configurar Gradle 8.9
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.9'

    - name: Crear local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > vlc-segovia-tv-main/local.properties

    - name: Compilar APK Debug
      run: |
        cd vlc-segovia-tv-main
        gradle wrapper --gradle-version 8.9
        chmod +x gradlew
        ./gradlew clean assembleDebug --no-daemon --stacktrace

    - name: Guardar APK
      uses: actions/upload-artifact@v4
      with:
        name: SegoviaTV-APK
        path: vlc-segovia-tv-main/**/build/outputs/apk/**/*.apk
        
